# Generated by Django 5.0.1 on 2024-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
